Add poll support
irazasyed/telegram-bot-sdk pull request #727
Opened 2020-04-01 12:31 UTC by arsamme

Completed poll properties

2020-04-07 22:46 UTC, irazasyed commented on .gitignore
> +.idea/
Please remove the `.idea` from this file. It should go in your global gitignore file.

2020-04-07 22:47 UTC, irazasyed requested changes
Please make the requested changes! Thanks.

2020-04-07 22:47 UTC, irazasyed commented on src/Objects/Message.php
>   */
Please maintain the code styling.

2020-04-07 22:47 UTC, irazasyed commented on src/Objects/Message.php
>          ];
Code styling!

2020-04-11 14:23 UTC, arsamme commented
@irazasyed Solved! Would you please review again?

2020-04-11 14:55 UTC, merged

2020-04-11 14:55 UTC, irazasyed commented
Thanks!